export {AdminLogin} from "./adminpanel/adminLogin/adminLogin";
export {Dashboard} from "./adminpanel/dashboard/dashboard";
export {Orders} from "./adminpanel/orders/orders";
export {ProductsList} from "./adminpanel/productsList/productsList";
export {Stock} from "./adminpanel/stock/stock";
export {Cart} from "./shop/cart/cart";
export {Category} from "./shop/category/category";
export {CustomerInfo } from "./shop/customerInfo/customerInfo";
export {IntroPage} from "./shop/introPage/introPage";
export {OrderSubmit} from "./shop/orderSubmit/orderSubmit";
export {PaymentResult} from "./shop/paymentResult/paymentResult";
export {ProductDetail} from "./shop/productDetail/productDetail";
export {AdminPanel} from "./adminpanel/adminPanel/adminPanel";
export {PageNotFound} from "./pageNot found/pageNotFound";